import './globals.css'
import TopNav from './TopNav';
import SideNav from './SideNav';


export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="bg-zinc-900 text-zinc-100">
        <div className="flex flex-col border-2 border-green-500 h-screen">
          <TopNav />
          <div className="flex flex-1 border-2 border-yellow-500">
            <SideNav />
            {children}
          </div>
        </div>
      </body>
    </html>
  )
}
